# Generated by Django 5.0.7 on 2024-08-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_article_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover",
            field=models.ImageField(
                blank=True, default="stock-article.jpg", upload_to="uploads/"
            ),
        ),
    ]
