# Generated by Django 5.0.7 on 2024-08-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_article_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="cover",
            field=models.ImageField(
                blank=True, default="media/stock-article.jpg", upload_to="uploads/"
            ),
        ),
    ]
