# Generated by Django 5.0.7 on 2024-08-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_rename_created_article_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="cover",
            field=models.ImageField(
                blank=True, default="stock-article.jpg", upload_to="uploads/"
            ),
        ),
    ]
