# Generated by Django 5.0.7 on 2024-10-17 18:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0011_alter_article_category_alter_article_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Текст записи"),
        ),
    ]
