# Generated by Django 5.0.7 on 2024-10-14 17:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0011_alter_article_category_alter_article_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="Текст записи"),
        ),
    ]
