# Generated by Django 5.1.2 on 2024-11-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен'),
        ),
    ]
